CREATE TABLE custumer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   fist_name VARCHAR(255) NOT NULL,
   last_name VARCHAR(255) NOT NULL,
   cpf VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   zip_code VARCHAR(255) NOT NULL,
   street VARCHAR(255) NOT NULL,
   CONSTRAINT pk_custumer PRIMARY KEY (id)
);

ALTER TABLE custumer ADD CONSTRAINT uc_custumer_cpf UNIQUE (cpf);

ALTER TABLE custumer ADD CONSTRAINT uc_custumer_email UNIQUE (email);